<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>net.freeutils</groupId>
        <artifactId>parent</artifactId>
        <version>1.0</version>
        <relativePath>../parent/pom.xml</relativePath>
    </parent>

    <artifactId>jtnef</artifactId>
    <version>2.0.0</version>
    <packaging>jar</packaging>

    <name>JTNEF</name>
    <description>The Java TNEF package</description>
    <url>http://www.freeutils.net/source/jtnef/</url>
    <licenses>
        <license>
            <name>GNU General Public License (GPL), Version 2.0</name>
            <url>http://www.gnu.org/licenses/gpl-2.0.html</url>
        </license>
        <license>
            <name>Commercial License</name>
            <url>LICENSE.commercial.txt</url>
        </license>
    </licenses>

    <properties>
        <jdk.version>1.5</jdk.version>
        <animal.sniffer.jdk.version>java15</animal.sniffer.jdk.version>
        <skip.assembly>false</skip.assembly>
    </properties>

    <dependencies>
        <dependency>
            <!-- only required when using the net.freeutils.tnef.mime package -->
            <groupId>com.sun.mail</groupId>
            <artifactId>javax.mail</artifactId>
            <version>1.5.4</version>
            <optional>true</optional>
        </dependency>
        <dependency>
            <!-- only required when using the net.freeutils.tnef.msg package -->
            <groupId>org.apache.poi</groupId>
            <artifactId>poi</artifactId>
            <version>3.13</version>
            <optional>true</optional>
        </dependency>
        <!-- only required for tests -->
        <dependency>
            <groupId>net.freeutils</groupId>
            <artifactId>jelementary</artifactId>
            <version>1.0</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <systemPropertyVariables>
                        <project.dir>${project.basedir}</project.dir>
                    </systemPropertyVariables>
                </configuration>
            </plugin>
            <!-- make it an OSGi bundle -->
            <plugin>
                <groupId>org.apache.felix</groupId>
                <artifactId>maven-bundle-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <configuration>
                    <!-- use the generated bundle manifest -->
                    <useDefaultManifestFile>true</useDefaultManifestFile>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
