var MailReader;
(function (MailReader) {
    var MSG;
    (function (MSG) {
        var Property = (function () {
            function Property(data, storage, offset) {
                var prop = MailReader.Util.Struct.parse(data, Property.type_set, offset);
                this.flags = prop.flags;
                this.tag = prop.tag;
                this.type = prop.type;
                this.storage = storage;
                this.data = new Uint8Array(prop.data).buffer;
            }
            Property.prototype.read = function () {
                var view = new DataView(this.data);
                switch (this.type) {
                    case Property.Type.PT_CLSID:
                    case Property.Type.PT_OBJECT:
                        return undefined;
                    case Property.Type.PT_BOOLEAN:
                        return (view.getUint8(0) != 0);
                    case Property.Type.PT_SHORT:
                        return view.getUint16(0, true);
                    case Property.Type.PT_ERROR:
                        return view.getInt32(0, true);
                    case Property.Type.PT_LONG:
                        return view.getUint32(0, true);
                    case Property.Type.PT_FLOAT:
                        return view.getFloat32(0, true);
                    case Property.Type.PT_APPTIME:
                    case Property.Type.PT_DOUBLE:
                        return view.getFloat64(0, true);
                    case Property.Type.PT_SYSTIME:
                    case Property.Type.PT_CURRENCY:
                    case Property.Type.PT_LONGLONG:
                        var l = view.getUint32(0, true);
                        var r = view.getUint32(4, true);
                        return (l + 4294967296 * r);
                }
                if (this.stream == undefined) {
                    var name_1 = Property.PREFIX +
                        ("0000" + this.tag.toString(16).toUpperCase()).slice(-4) +
                        ("0000" + this.type.toString(16).toUpperCase()).slice(-4);
                    this.stream = this.storage.getStream(name_1);
                    if (this.stream == undefined) {
                        throw new Error("[MSG::Property::read] " +
                            "Stream is missing for property " + name_1 + ".");
                    }
                }
                switch (this.type) {
                    case Property.Type.PT_BINARY:
                        return this.stream.read();
                    case Property.Type.PT_STRING8:
                        var l1 = view.getUint32(0, true);
                        return this.stream.read(l1 - 1);
                    case Property.Type.PT_UNICODE:
                        var l2 = view.getUint32(0, true);
                        return this.stream.read(l2 - 2);
                }
                return undefined;
            };
            return Property;
        }());
        Property.type_set = {
            type: 'uint16',
            tag: 'uint16',
            flags: 'uint32',
            data: ['uint8', 8]
        };
        Property.PREFIX = "__substg1.0_";
        MSG.Property = Property;
        (function (Property) {
            var Type;
            (function (Type) {
                Type[Type["PT_UNSPECIFIED"] = 0] = "PT_UNSPECIFIED";
                Type[Type["PT_NULL"] = 1] = "PT_NULL";
                Type[Type["PT_SHORT"] = 2] = "PT_SHORT";
                Type[Type["PT_LONG"] = 3] = "PT_LONG";
                Type[Type["PT_FLOAT"] = 4] = "PT_FLOAT";
                Type[Type["PT_DOUBLE"] = 5] = "PT_DOUBLE";
                Type[Type["PT_BOOLEAN"] = 11] = "PT_BOOLEAN";
                Type[Type["PT_CURRENCY"] = 6] = "PT_CURRENCY";
                Type[Type["PT_APPTIME"] = 7] = "PT_APPTIME";
                Type[Type["PT_SYSTIME"] = 64] = "PT_SYSTIME";
                Type[Type["PT_LONGLONG"] = 20] = "PT_LONGLONG";
                Type[Type["PT_ERROR"] = 10] = "PT_ERROR";
                Type[Type["PT_UNICODE"] = 31] = "PT_UNICODE";
                Type[Type["PT_BINARY"] = 258] = "PT_BINARY";
                Type[Type["PT_STRING8"] = 30] = "PT_STRING8";
                Type[Type["PT_CLSID"] = 72] = "PT_CLSID";
                Type[Type["PT_OBJECT"] = 13] = "PT_OBJECT";
                Type[Type["MV_FLAG"] = 4096] = "MV_FLAG";
                Type[Type["PT_MV_SHORT"] = 4098] = "PT_MV_SHORT";
                Type[Type["PT_MV_LONG"] = 4099] = "PT_MV_LONG";
                Type[Type["PT_MV_FLOAT"] = 4100] = "PT_MV_FLOAT";
                Type[Type["PT_MV_DOUBLE"] = 4101] = "PT_MV_DOUBLE";
                Type[Type["PT_MV_CURRENCY"] = 4102] = "PT_MV_CURRENCY";
                Type[Type["PT_MV_APPTIME"] = 4103] = "PT_MV_APPTIME";
                Type[Type["PT_MV_LONGLONG"] = 4116] = "PT_MV_LONGLONG";
                Type[Type["PT_MV_STRING8"] = 4126] = "PT_MV_STRING8";
                Type[Type["PT_MV_UNICODE"] = 4127] = "PT_MV_UNICODE";
                Type[Type["PT_MV_SYSTIME"] = 4160] = "PT_MV_SYSTIME";
                Type[Type["PT_MV_CLSID"] = 4168] = "PT_MV_CLSID";
                Type[Type["PT_MV_BINARY"] = 4354] = "PT_MV_BINARY";
            })(Type = Property.Type || (Property.Type = {}));
            var Tag;
            (function (Tag) {
                Tag[Tag["PidTagAccess"] = 4084] = "PidTagAccess";
                Tag[Tag["PidTagAccessControlListData"] = 16352] = "PidTagAccessControlListData";
                Tag[Tag["PidTagAccessLevel"] = 4087] = "PidTagAccessLevel";
                Tag[Tag["PidTagAccount"] = 14848] = "PidTagAccount";
                Tag[Tag["PidTagAdditionalRenEntryIds"] = 14040] = "PidTagAdditionalRenEntryIds";
                Tag[Tag["PidTagAdditionalRenEntryIdsEx"] = 14041] = "PidTagAdditionalRenEntryIdsEx";
                Tag[Tag["PidTagAddressBookAuthorizedSenders"] = 36056] = "PidTagAddressBookAuthorizedSenders";
                Tag[Tag["PidTagAddressBookContainerId"] = 65533] = "PidTagAddressBookContainerId";
                Tag[Tag["PidTagAddressBookDeliveryContentLength"] = 32874] = "PidTagAddressBookDeliveryContentLength";
                Tag[Tag["PidTagAddressBookDisplayNamePrintable"] = 14847] = "PidTagAddressBookDisplayNamePrintable";
                Tag[Tag["PidTagAddressBookDisplayTypeExtended"] = 35987] = "PidTagAddressBookDisplayTypeExtended";
                Tag[Tag["PidTagAddressBookDistributionListExternalMemberCount"] = 36067] = "PidTagAddressBookDistributionListExternalMemberCount";
                Tag[Tag["PidTagAddressBookDistributionListMemberCount"] = 36066] = "PidTagAddressBookDistributionListMemberCount";
                Tag[Tag["PidTagAddressBookDistributionListMemberSubmitAccepted"] = 32883] = "PidTagAddressBookDistributionListMemberSubmitAccepted";
                Tag[Tag["PidTagAddressBookDistributionListMemberSubmitRejected"] = 36058] = "PidTagAddressBookDistributionListMemberSubmitRejected";
                Tag[Tag["PidTagAddressBookDistributionListRejectMessagesFromDLMembers"] = 36059] = "PidTagAddressBookDistributionListRejectMessagesFromDLMembers";
                Tag[Tag["PidTagAddressBookEntryId"] = 26171] = "PidTagAddressBookEntryId";
                Tag[Tag["PidTagAddressBookExtensionAttribute10"] = 32822] = "PidTagAddressBookExtensionAttribute10";
                Tag[Tag["PidTagAddressBookExtensionAttribute11"] = 35927] = "PidTagAddressBookExtensionAttribute11";
                Tag[Tag["PidTagAddressBookExtensionAttribute12"] = 35928] = "PidTagAddressBookExtensionAttribute12";
                Tag[Tag["PidTagAddressBookExtensionAttribute13"] = 35929] = "PidTagAddressBookExtensionAttribute13";
                Tag[Tag["PidTagAddressBookExtensionAttribute14"] = 35936] = "PidTagAddressBookExtensionAttribute14";
                Tag[Tag["PidTagAddressBookExtensionAttribute15"] = 35937] = "PidTagAddressBookExtensionAttribute15";
                Tag[Tag["PidTagAddressBookExtensionAttribute1"] = 32813] = "PidTagAddressBookExtensionAttribute1";
                Tag[Tag["PidTagAddressBookExtensionAttribute2"] = 32814] = "PidTagAddressBookExtensionAttribute2";
                Tag[Tag["PidTagAddressBookExtensionAttribute3"] = 32815] = "PidTagAddressBookExtensionAttribute3";
                Tag[Tag["PidTagAddressBookExtensionAttribute4"] = 32816] = "PidTagAddressBookExtensionAttribute4";
                Tag[Tag["PidTagAddressBookExtensionAttribute5"] = 32817] = "PidTagAddressBookExtensionAttribute5";
                Tag[Tag["PidTagAddressBookExtensionAttribute6"] = 32818] = "PidTagAddressBookExtensionAttribute6";
                Tag[Tag["PidTagAddressBookExtensionAttribute7"] = 32819] = "PidTagAddressBookExtensionAttribute7";
                Tag[Tag["PidTagAddressBookExtensionAttribute8"] = 32820] = "PidTagAddressBookExtensionAttribute8";
                Tag[Tag["PidTagAddressBookExtensionAttribute9"] = 32821] = "PidTagAddressBookExtensionAttribute9";
                Tag[Tag["PidTagAddressBookFolderPathname"] = 32772] = "PidTagAddressBookFolderPathname";
                Tag[Tag["PidTagAddressBookHierarchicalChildDepartments"] = 35994] = "PidTagAddressBookHierarchicalChildDepartments";
                Tag[Tag["PidTagAddressBookHierarchicalDepartmentMembers"] = 35991] = "PidTagAddressBookHierarchicalDepartmentMembers";
                Tag[Tag["PidTagAddressBookHierarchicalIsHierarchicalGroup"] = 36061] = "PidTagAddressBookHierarchicalIsHierarchicalGroup";
                Tag[Tag["PidTagAddressBookHierarchicalParentDepartment"] = 35993] = "PidTagAddressBookHierarchicalParentDepartment";
                Tag[Tag["PidTagAddressBookHierarchicalRootDepartment"] = 35992] = "PidTagAddressBookHierarchicalRootDepartment";
                Tag[Tag["PidTagAddressBookHierarchicalShowInDepartments"] = 35988] = "PidTagAddressBookHierarchicalShowInDepartments";
                Tag[Tag["PidTagAddressBookHomeMessageDatabase"] = 32774] = "PidTagAddressBookHomeMessageDatabase";
                Tag[Tag["PidTagAddressBookIsMaster"] = 65531] = "PidTagAddressBookIsMaster";
                Tag[Tag["PidTagAddressBookIsMemberOfDistributionList"] = 32776] = "PidTagAddressBookIsMemberOfDistributionList";
                Tag[Tag["PidTagAddressBookManageDistributionList"] = 26372] = "PidTagAddressBookManageDistributionList";
                Tag[Tag["PidTagAddressBookManager"] = 32773] = "PidTagAddressBookManager";
                Tag[Tag["PidTagAddressBookManagerDistinguishedName"] = 32773] = "PidTagAddressBookManagerDistinguishedName";
                Tag[Tag["PidTagAddressBookMember"] = 32777] = "PidTagAddressBookMember";
                Tag[Tag["PidTagAddressBookMessageId"] = 26447] = "PidTagAddressBookMessageId";
                Tag[Tag["PidTagAddressBookModerationEnabled"] = 36021] = "PidTagAddressBookModerationEnabled";
                Tag[Tag["PidTagAddressBookNetworkAddress"] = 33136] = "PidTagAddressBookNetworkAddress";
                Tag[Tag["PidTagAddressBookObjectDistinguishedName"] = 32828] = "PidTagAddressBookObjectDistinguishedName";
                Tag[Tag["PidTagAddressBookObjectGuid"] = 35949] = "PidTagAddressBookObjectGuid";
                Tag[Tag["PidTagAddressBookOrganizationalUnitRootDistinguishedName"] = 36008] = "PidTagAddressBookOrganizationalUnitRootDistinguishedName";
                Tag[Tag["PidTagAddressBookOwner"] = 32780] = "PidTagAddressBookOwner";
                Tag[Tag["PidTagAddressBookOwnerBackLink"] = 32804] = "PidTagAddressBookOwnerBackLink";
                Tag[Tag["PidTagAddressBookParentEntryId"] = 65532] = "PidTagAddressBookParentEntryId";
                Tag[Tag["PidTagAddressBookPhoneticCompanyName"] = 35985] = "PidTagAddressBookPhoneticCompanyName";
                Tag[Tag["PidTagAddressBookPhoneticDepartmentName"] = 35984] = "PidTagAddressBookPhoneticDepartmentName";
                Tag[Tag["PidTagAddressBookPhoneticDisplayName"] = 35986] = "PidTagAddressBookPhoneticDisplayName";
                Tag[Tag["PidTagAddressBookPhoneticGivenName"] = 35982] = "PidTagAddressBookPhoneticGivenName";
                Tag[Tag["PidTagAddressBookPhoneticSurname"] = 35983] = "PidTagAddressBookPhoneticSurname";
                Tag[Tag["PidTagAddressBookProxyAddresses"] = 32783] = "PidTagAddressBookProxyAddresses";
                Tag[Tag["PidTagAddressBookPublicDelegates"] = 32789] = "PidTagAddressBookPublicDelegates";
                Tag[Tag["PidTagAddressBookReports"] = 32782] = "PidTagAddressBookReports";
                Tag[Tag["PidTagAddressBookRoomCapacity"] = 2055] = "PidTagAddressBookRoomCapacity";
                Tag[Tag["PidTagAddressBookRoomContainers"] = 35990] = "PidTagAddressBookRoomContainers";
                Tag[Tag["PidTagAddressBookRoomDescription"] = 2057] = "PidTagAddressBookRoomDescription";
                Tag[Tag["PidTagAddressBookSenderHintTranslations"] = 36012] = "PidTagAddressBookSenderHintTranslations";
                Tag[Tag["PidTagAddressBookSeniorityIndex"] = 36000] = "PidTagAddressBookSeniorityIndex";
                Tag[Tag["PidTagAddressBookTargetAddress"] = 32785] = "PidTagAddressBookTargetAddress";
                Tag[Tag["PidTagAddressBookUnauthorizedSenders"] = 36057] = "PidTagAddressBookUnauthorizedSenders";
                Tag[Tag["PidTagAddressBookX509Certificate"] = 35946] = "PidTagAddressBookX509Certificate";
                Tag[Tag["PidTagAddressType"] = 12290] = "PidTagAddressType";
                Tag[Tag["PidTagAlternateRecipientAllowed"] = 2] = "PidTagAlternateRecipientAllowed";
                Tag[Tag["PidTagAnr"] = 13836] = "PidTagAnr";
                Tag[Tag["PidTagArchiveDate"] = 12319] = "PidTagArchiveDate";
                Tag[Tag["PidTagArchivePeriod"] = 12318] = "PidTagArchivePeriod";
                Tag[Tag["PidTagArchiveTag"] = 12312] = "PidTagArchiveTag";
                Tag[Tag["PidTagAssistantTelephoneNumber"] = 14894] = "PidTagAssistantTelephoneNumber";
                Tag[Tag["PidTagAssistant"] = 14896] = "PidTagAssistant";
                Tag[Tag["PidTagAssociated"] = 26538] = "PidTagAssociated";
                Tag[Tag["PidTagAttachAdditionalInformation"] = 14095] = "PidTagAttachAdditionalInformation";
                Tag[Tag["PidTagAttachContentBase"] = 14097] = "PidTagAttachContentBase";
                Tag[Tag["PidTagAttachContentId"] = 14098] = "PidTagAttachContentId";
                Tag[Tag["PidTagAttachContentLocation"] = 14099] = "PidTagAttachContentLocation";
                Tag[Tag["PidTagAttachDataBinary"] = 14081] = "PidTagAttachDataBinary";
                Tag[Tag["PidTagAttachDataObject"] = 14081] = "PidTagAttachDataObject";
                Tag[Tag["PidTagAttachEncoding"] = 14082] = "PidTagAttachEncoding";
                Tag[Tag["PidTagAttachExtension"] = 14083] = "PidTagAttachExtension";
                Tag[Tag["PidTagAttachFilename"] = 14084] = "PidTagAttachFilename";
                Tag[Tag["PidTagAttachFlags"] = 14100] = "PidTagAttachFlags";
                Tag[Tag["PidTagAttachLongFilename"] = 14087] = "PidTagAttachLongFilename";
                Tag[Tag["PidTagAttachLongPathname"] = 14093] = "PidTagAttachLongPathname";
                Tag[Tag["PidTagAttachMethod"] = 14085] = "PidTagAttachMethod";
                Tag[Tag["PidTagAttachMimeTag"] = 14094] = "PidTagAttachMimeTag";
                Tag[Tag["PidTagAttachNumber"] = 3617] = "PidTagAttachNumber";
                Tag[Tag["PidTagAttachPathname"] = 14088] = "PidTagAttachPathname";
                Tag[Tag["PidTagAttachPayloadClass"] = 14106] = "PidTagAttachPayloadClass";
                Tag[Tag["PidTagAttachPayloadProviderGuidString"] = 14105] = "PidTagAttachPayloadProviderGuidString";
                Tag[Tag["PidTagAttachRendering"] = 14089] = "PidTagAttachRendering";
                Tag[Tag["PidTagAttachSize"] = 3616] = "PidTagAttachSize";
                Tag[Tag["PidTagAttachTag"] = 14090] = "PidTagAttachTag";
                Tag[Tag["PidTagAttachTransportName"] = 14092] = "PidTagAttachTransportName";
                Tag[Tag["PidTagAttachmentContactPhoto"] = 32767] = "PidTagAttachmentContactPhoto";
                Tag[Tag["PidTagAttachmentFlags"] = 32765] = "PidTagAttachmentFlags";
                Tag[Tag["PidTagAttachmentHidden"] = 32766] = "PidTagAttachmentHidden";
                Tag[Tag["PidTagAttachmentLinkId"] = 32762] = "PidTagAttachmentLinkId";
                Tag[Tag["PidTagAttributeHidden"] = 4340] = "PidTagAttributeHidden";
                Tag[Tag["PidTagAttributeReadOnly"] = 4342] = "PidTagAttributeReadOnly";
                Tag[Tag["PidTagAutoForwardComment"] = 4] = "PidTagAutoForwardComment";
                Tag[Tag["PidTagAutoForwarded"] = 5] = "PidTagAutoForwarded";
                Tag[Tag["PidTagAutoResponseSuppress"] = 16351] = "PidTagAutoResponseSuppress";
                Tag[Tag["PidTagBirthday"] = 14914] = "PidTagBirthday";
                Tag[Tag["PidTagBlockStatus"] = 4246] = "PidTagBlockStatus";
                Tag[Tag["PidTagBodyContentId"] = 4117] = "PidTagBodyContentId";
                Tag[Tag["PidTagBodyContentLocation"] = 4116] = "PidTagBodyContentLocation";
                Tag[Tag["PidTagBodyHtml"] = 4115] = "PidTagBodyHtml";
                Tag[Tag["PidTagBody"] = 4096] = "PidTagBody";
                Tag[Tag["PidTagBusiness2TelephoneNumber"] = 14875] = "PidTagBusiness2TelephoneNumber";
                Tag[Tag["PidTagBusiness2TelephoneNumbers"] = 14875] = "PidTagBusiness2TelephoneNumbers";
                Tag[Tag["PidTagBusinessFaxNumber"] = 14884] = "PidTagBusinessFaxNumber";
                Tag[Tag["PidTagBusinessHomePage"] = 14929] = "PidTagBusinessHomePage";
                Tag[Tag["PidTagBusinessTelephoneNumber"] = 14856] = "PidTagBusinessTelephoneNumber";
                Tag[Tag["PidTagCallId"] = 26630] = "PidTagCallId";
                Tag[Tag["PidTagCallbackTelephoneNumber"] = 14850] = "PidTagCallbackTelephoneNumber";
                Tag[Tag["PidTagCarTelephoneNumber"] = 14878] = "PidTagCarTelephoneNumber";
                Tag[Tag["PidTagCdoRecurrenceid"] = 4293] = "PidTagCdoRecurrenceid";
                Tag[Tag["PidTagChangeKey"] = 26082] = "PidTagChangeKey";
                Tag[Tag["PidTagChangeNumber"] = 26532] = "PidTagChangeNumber";
                Tag[Tag["PidTagChildrensNames"] = 14936] = "PidTagChildrensNames";
                Tag[Tag["PidTagClientActions"] = 26181] = "PidTagClientActions";
                Tag[Tag["PidTagClientSubmitTime"] = 57] = "PidTagClientSubmitTime";
                Tag[Tag["PidTagCodePageId"] = 26307] = "PidTagCodePageId";
                Tag[Tag["PidTagComment"] = 12292] = "PidTagComment";
                Tag[Tag["PidTagCompanyMainTelephoneNumber"] = 14935] = "PidTagCompanyMainTelephoneNumber";
                Tag[Tag["PidTagCompanyName"] = 14870] = "PidTagCompanyName";
                Tag[Tag["PidTagComputerNetworkName"] = 14921] = "PidTagComputerNetworkName";
                Tag[Tag["PidTagConflictEntryId"] = 16368] = "PidTagConflictEntryId";
                Tag[Tag["PidTagContainerClass"] = 13843] = "PidTagContainerClass";
                Tag[Tag["PidTagContainerContents"] = 13839] = "PidTagContainerContents";
                Tag[Tag["PidTagContainerFlags"] = 13824] = "PidTagContainerFlags";
                Tag[Tag["PidTagContainerHierarchy"] = 13838] = "PidTagContainerHierarchy";
                Tag[Tag["PidTagContentCount"] = 13826] = "PidTagContentCount";
                Tag[Tag["PidTagContentFilterSpamConfidenceLevel"] = 16502] = "PidTagContentFilterSpamConfidenceLevel";
                Tag[Tag["PidTagContentUnreadCount"] = 13827] = "PidTagContentUnreadCount";
                Tag[Tag["PidTagConversationId"] = 12307] = "PidTagConversationId";
                Tag[Tag["PidTagConversationIndex"] = 113] = "PidTagConversationIndex";
                Tag[Tag["PidTagConversationIndexTracking"] = 12310] = "PidTagConversationIndexTracking";
                Tag[Tag["PidTagConversationTopic"] = 112] = "PidTagConversationTopic";
                Tag[Tag["PidTagCountry"] = 14886] = "PidTagCountry";
                Tag[Tag["PidTagCreationTime"] = 12295] = "PidTagCreationTime";
                Tag[Tag["PidTagCreatorEntryId"] = 16377] = "PidTagCreatorEntryId";
                Tag[Tag["PidTagCreatorName"] = 16376] = "PidTagCreatorName";
                Tag[Tag["PidTagCustomerId"] = 14922] = "PidTagCustomerId";
                Tag[Tag["PidTagDamBackPatched"] = 26183] = "PidTagDamBackPatched";
                Tag[Tag["PidTagDamOriginalEntryId"] = 26182] = "PidTagDamOriginalEntryId";
                Tag[Tag["PidTagDefaultPostMessageClass"] = 14053] = "PidTagDefaultPostMessageClass";
                Tag[Tag["PidTagDeferredActionMessageOriginalEntryId"] = 26433] = "PidTagDeferredActionMessageOriginalEntryId";
                Tag[Tag["PidTagDeferredDeliveryTime"] = 15] = "PidTagDeferredDeliveryTime";
                Tag[Tag["PidTagDeferredSendNumber"] = 16363] = "PidTagDeferredSendNumber";
                Tag[Tag["PidTagDeferredSendTime"] = 16367] = "PidTagDeferredSendTime";
                Tag[Tag["PidTagDeferredSendUnits"] = 16364] = "PidTagDeferredSendUnits";
                Tag[Tag["PidTagDelegateFlags"] = 26731] = "PidTagDelegateFlags";
                Tag[Tag["PidTagDelegatedByRule"] = 16355] = "PidTagDelegatedByRule";
                Tag[Tag["PidTagDeleteAfterSubmit"] = 3585] = "PidTagDeleteAfterSubmit";
                Tag[Tag["PidTagDeletedCountTotal"] = 26379] = "PidTagDeletedCountTotal";
                Tag[Tag["PidTagDeletedOn"] = 26255] = "PidTagDeletedOn";
                Tag[Tag["PidTagDeliverTime"] = 16] = "PidTagDeliverTime";
                Tag[Tag["PidTagDepartmentName"] = 14872] = "PidTagDepartmentName";
                Tag[Tag["PidTagDepth"] = 12293] = "PidTagDepth";
                Tag[Tag["PidTagDisplayBcc"] = 3586] = "PidTagDisplayBcc";
                Tag[Tag["PidTagDisplayCc"] = 3587] = "PidTagDisplayCc";
                Tag[Tag["PidTagDisplayNamePrefix"] = 14917] = "PidTagDisplayNamePrefix";
                Tag[Tag["PidTagDisplayName"] = 12289] = "PidTagDisplayName";
                Tag[Tag["PidTagDisplayTo"] = 3588] = "PidTagDisplayTo";
                Tag[Tag["PidTagDisplayType"] = 14592] = "PidTagDisplayType";
                Tag[Tag["PidTagDisplayTypeEx"] = 14597] = "PidTagDisplayTypeEx";
                Tag[Tag["PidTagEmailAddress"] = 12291] = "PidTagEmailAddress";
                Tag[Tag["PidTagEndDate"] = 97] = "PidTagEndDate";
                Tag[Tag["PidTagEntryId"] = 4095] = "PidTagEntryId";
                Tag[Tag["PidTagExceptionEndTime"] = 32764] = "PidTagExceptionEndTime";
                Tag[Tag["PidTagExceptionReplaceTime"] = 32761] = "PidTagExceptionReplaceTime";
                Tag[Tag["PidTagExceptionStartTime"] = 32763] = "PidTagExceptionStartTime";
                Tag[Tag["PidTagExchangeNTSecurityDescriptor"] = 3716] = "PidTagExchangeNTSecurityDescriptor";
                Tag[Tag["PidTagExpiryNumber"] = 16365] = "PidTagExpiryNumber";
                Tag[Tag["PidTagExpiryTime"] = 21] = "PidTagExpiryTime";
                Tag[Tag["PidTagExpiryUnits"] = 16366] = "PidTagExpiryUnits";
                Tag[Tag["PidTagExtendedFolderFlags"] = 14042] = "PidTagExtendedFolderFlags";
                Tag[Tag["PidTagExtendedRuleMessageActions"] = 3737] = "PidTagExtendedRuleMessageActions";
                Tag[Tag["PidTagExtendedRuleMessageCondition"] = 3738] = "PidTagExtendedRuleMessageCondition";
                Tag[Tag["PidTagExtendedRuleSizeLimit"] = 3739] = "PidTagExtendedRuleSizeLimit";
                Tag[Tag["PidTagFaxNumberOfPages"] = 26628] = "PidTagFaxNumberOfPages";
                Tag[Tag["PidTagFlagCompleteTime"] = 4241] = "PidTagFlagCompleteTime";
                Tag[Tag["PidTagFlagStatus"] = 4240] = "PidTagFlagStatus";
                Tag[Tag["PidTagFlatUrlName"] = 26382] = "PidTagFlatUrlName";
                Tag[Tag["PidTagFolderAssociatedContents"] = 13840] = "PidTagFolderAssociatedContents";
                Tag[Tag["PidTagFolderId"] = 26440] = "PidTagFolderId";
                Tag[Tag["PidTagFolderType"] = 13825] = "PidTagFolderType";
                Tag[Tag["PidTagFollowupIcon"] = 4245] = "PidTagFollowupIcon";
                Tag[Tag["PidTagFreeBusyCountMonths"] = 26729] = "PidTagFreeBusyCountMonths";
                Tag[Tag["PidTagFreeBusyEntryIds"] = 14052] = "PidTagFreeBusyEntryIds";
                Tag[Tag["PidTagFreeBusyMessageEmailAddress"] = 26697] = "PidTagFreeBusyMessageEmailAddress";
                Tag[Tag["PidTagFreeBusyPublishEnd"] = 26696] = "PidTagFreeBusyPublishEnd";
                Tag[Tag["PidTagFreeBusyPublishStart"] = 26695] = "PidTagFreeBusyPublishStart";
                Tag[Tag["PidTagFreeBusyRangeTimestamp"] = 26728] = "PidTagFreeBusyRangeTimestamp";
                Tag[Tag["PidTagFtpSite"] = 14924] = "PidTagFtpSite";
                Tag[Tag["PidTagGatewayNeedsToRefresh"] = 26694] = "PidTagGatewayNeedsToRefresh";
                Tag[Tag["PidTagGender"] = 14925] = "PidTagGender";
                Tag[Tag["PidTagGeneration"] = 14853] = "PidTagGeneration";
                Tag[Tag["PidTagGivenName"] = 14854] = "PidTagGivenName";
                Tag[Tag["PidTagGovernmentIdNumber"] = 14855] = "PidTagGovernmentIdNumber";
                Tag[Tag["PidTagHasAttachments"] = 3611] = "PidTagHasAttachments";
                Tag[Tag["PidTagHasDeferredActionMessages"] = 16362] = "PidTagHasDeferredActionMessages";
                Tag[Tag["PidTagHasNamedProperties"] = 26186] = "PidTagHasNamedProperties";
                Tag[Tag["PidTagHasRules"] = 26170] = "PidTagHasRules";
                Tag[Tag["PidTagHierarchyChangeNumber"] = 26174] = "PidTagHierarchyChangeNumber";
                Tag[Tag["PidTagHobbies"] = 14915] = "PidTagHobbies";
                Tag[Tag["PidTagHome2TelephoneNumber"] = 14895] = "PidTagHome2TelephoneNumber";
                Tag[Tag["PidTagHome2TelephoneNumbers"] = 14895] = "PidTagHome2TelephoneNumbers";
                Tag[Tag["PidTagHomeAddressCity"] = 14937] = "PidTagHomeAddressCity";
                Tag[Tag["PidTagHomeAddressCountry"] = 14938] = "PidTagHomeAddressCountry";
                Tag[Tag["PidTagHomeAddressPostOfficeBox"] = 14942] = "PidTagHomeAddressPostOfficeBox";
                Tag[Tag["PidTagHomeAddressPostalCode"] = 14939] = "PidTagHomeAddressPostalCode";
                Tag[Tag["PidTagHomeAddressStateOrProvince"] = 14940] = "PidTagHomeAddressStateOrProvince";
                Tag[Tag["PidTagHomeAddressStreet"] = 14941] = "PidTagHomeAddressStreet";
                Tag[Tag["PidTagHomeFaxNumber"] = 14885] = "PidTagHomeFaxNumber";
                Tag[Tag["PidTagHomeTelephoneNumber"] = 14857] = "PidTagHomeTelephoneNumber";
                Tag[Tag["PidTagHtml"] = 4115] = "PidTagHtml";
                Tag[Tag["PidTagICalendarEndTime"] = 4292] = "PidTagICalendarEndTime";
                Tag[Tag["PidTagICalendarReminderNextTime"] = 4298] = "PidTagICalendarReminderNextTime";
                Tag[Tag["PidTagICalendarStartTime"] = 4291] = "PidTagICalendarStartTime";
                Tag[Tag["PidTagIconIndex"] = 4224] = "PidTagIconIndex";
                Tag[Tag["PidTagImportance"] = 23] = "PidTagImportance";
                Tag[Tag["PidTagInConflict"] = 26220] = "PidTagInConflict";
                Tag[Tag["PidTagInReplyToId"] = 4162] = "PidTagInReplyToId";
                Tag[Tag["PidTagInitialDetailsPane"] = 16136] = "PidTagInitialDetailsPane";
                Tag[Tag["PidTagInitials"] = 14858] = "PidTagInitials";
                Tag[Tag["PidTagInstID"] = 26445] = "PidTagInstID";
                Tag[Tag["PidTagInstanceKey"] = 4086] = "PidTagInstanceKey";
                Tag[Tag["PidTagInstanceNum"] = 26446] = "PidTagInstanceNum";
                Tag[Tag["PidTagInternetCodepage"] = 16350] = "PidTagInternetCodepage";
                Tag[Tag["PidTagInternetMailOverrideFormat"] = 22786] = "PidTagInternetMailOverrideFormat";
                Tag[Tag["PidTagInternetMessageId"] = 4149] = "PidTagInternetMessageId";
                Tag[Tag["PidTagInternetReferences"] = 4153] = "PidTagInternetReferences";
                Tag[Tag["PidTagIpmAppointmentEntryId"] = 14032] = "PidTagIpmAppointmentEntryId";
                Tag[Tag["PidTagIpmContactEntryId"] = 14033] = "PidTagIpmContactEntryId";
                Tag[Tag["PidTagIpmDraftsEntryId"] = 14039] = "PidTagIpmDraftsEntryId";
                Tag[Tag["PidTagIpmJournalEntryId"] = 14034] = "PidTagIpmJournalEntryId";
                Tag[Tag["PidTagIpmNoteEntryId"] = 14035] = "PidTagIpmNoteEntryId";
                Tag[Tag["PidTagIpmTaskEntryId"] = 14036] = "PidTagIpmTaskEntryId";
                Tag[Tag["PidTagIsdnNumber"] = 14893] = "PidTagIsdnNumber";
                Tag[Tag["PidTagJunkAddRecipientsToSafeSendersList"] = 24835] = "PidTagJunkAddRecipientsToSafeSendersList";
                Tag[Tag["PidTagJunkIncludeContacts"] = 24832] = "PidTagJunkIncludeContacts";
                Tag[Tag["PidTagJunkPermanentlyDelete"] = 24834] = "PidTagJunkPermanentlyDelete";
                Tag[Tag["PidTagJunkPhishingEnableLinks"] = 24839] = "PidTagJunkPhishingEnableLinks";
                Tag[Tag["PidTagJunkThreshold"] = 24833] = "PidTagJunkThreshold";
                Tag[Tag["PidTagKeyword"] = 14859] = "PidTagKeyword";
                Tag[Tag["PidTagLanguage"] = 14860] = "PidTagLanguage";
                Tag[Tag["PidTagLastModificationTime"] = 12296] = "PidTagLastModificationTime";
                Tag[Tag["PidTagLastModifierEntryId"] = 16379] = "PidTagLastModifierEntryId";
                Tag[Tag["PidTagLastModifierName"] = 16378] = "PidTagLastModifierName";
                Tag[Tag["PidTagLastVerbExecuted"] = 4225] = "PidTagLastVerbExecuted";
                Tag[Tag["PidTagLastVerbExecutionTime"] = 4226] = "PidTagLastVerbExecutionTime";
                Tag[Tag["PidTagListHelp"] = 4163] = "PidTagListHelp";
                Tag[Tag["PidTagListSubscribe"] = 4164] = "PidTagListSubscribe";
                Tag[Tag["PidTagListUnsubscribe"] = 4165] = "PidTagListUnsubscribe";
                Tag[Tag["PidTagLocalCommitTime"] = 26377] = "PidTagLocalCommitTime";
                Tag[Tag["PidTagLocalCommitTimeMax"] = 26378] = "PidTagLocalCommitTimeMax";
                Tag[Tag["PidTagLocaleId"] = 26273] = "PidTagLocaleId";
                Tag[Tag["PidTagLocality"] = 14887] = "PidTagLocality";
                Tag[Tag["PidTagLocation"] = 14861] = "PidTagLocation";
                Tag[Tag["PidTagMailboxOwnerEntryId"] = 26139] = "PidTagMailboxOwnerEntryId";
                Tag[Tag["PidTagMailboxOwnerName"] = 26140] = "PidTagMailboxOwnerName";
                Tag[Tag["PidTagManagerName"] = 14926] = "PidTagManagerName";
                Tag[Tag["PidTagMappingSignature"] = 4088] = "PidTagMappingSignature";
                Tag[Tag["PidTagMaximumSubmitMessageSize"] = 26221] = "PidTagMaximumSubmitMessageSize";
                Tag[Tag["PidTagMemberId"] = 26225] = "PidTagMemberId";
                Tag[Tag["PidTagMemberName"] = 26226] = "PidTagMemberName";
                Tag[Tag["PidTagMemberRights"] = 26227] = "PidTagMemberRights";
                Tag[Tag["PidTagMessageAttachments"] = 3603] = "PidTagMessageAttachments";
                Tag[Tag["PidTagMessageCcMe"] = 88] = "PidTagMessageCcMe";
                Tag[Tag["PidTagMessageClass"] = 26] = "PidTagMessageClass";
                Tag[Tag["PidTagMessageCodepage"] = 16381] = "PidTagMessageCodepage";
                Tag[Tag["PidTagMessageDeliveryTime"] = 3590] = "PidTagMessageDeliveryTime";
                Tag[Tag["PidTagMessageEditorFormat"] = 22793] = "PidTagMessageEditorFormat";
                Tag[Tag["PidTagMessageFlags"] = 3591] = "PidTagMessageFlags";
                Tag[Tag["PidTagMessageHandlingSystemCommonName"] = 14863] = "PidTagMessageHandlingSystemCommonName";
                Tag[Tag["PidTagMessageLocaleId"] = 16369] = "PidTagMessageLocaleId";
                Tag[Tag["PidTagMessageRecipientMe"] = 89] = "PidTagMessageRecipientMe";
                Tag[Tag["PidTagMessageRecipients"] = 3602] = "PidTagMessageRecipients";
                Tag[Tag["PidTagMessageSize"] = 3592] = "PidTagMessageSize";
                Tag[Tag["PidTagMessageSizeExtended"] = 3592] = "PidTagMessageSizeExtended";
                Tag[Tag["PidTagMessageStatus"] = 3607] = "PidTagMessageStatus";
                Tag[Tag["PidTagMessageSubmissionId"] = 71] = "PidTagMessageSubmissionId";
                Tag[Tag["PidTagMessageToMe"] = 87] = "PidTagMessageToMe";
                Tag[Tag["PidTagMid"] = 26442] = "PidTagMid";
                Tag[Tag["PidTagMiddleName"] = 14916] = "PidTagMiddleName";
                Tag[Tag["PidTagMimeSkeleton"] = 25840] = "PidTagMimeSkeleton";
                Tag[Tag["PidTagMobileTelephoneNumber"] = 14876] = "PidTagMobileTelephoneNumber";
                Tag[Tag["PidTagNativeBody"] = 4118] = "PidTagNativeBody";
                Tag[Tag["PidTagNextSendAcct"] = 3625] = "PidTagNextSendAcct";
                Tag[Tag["PidTagNickname"] = 14927] = "PidTagNickname";
                Tag[Tag["PidTagNonDeliveryReportDiagCode"] = 3077] = "PidTagNonDeliveryReportDiagCode";
                Tag[Tag["PidTagNonDeliveryReportReasonCode"] = 3076] = "PidTagNonDeliveryReportReasonCode";
                Tag[Tag["PidTagNonDeliveryReportStatusCode"] = 3104] = "PidTagNonDeliveryReportStatusCode";
                Tag[Tag["PidTagNormalizedSubject"] = 3613] = "PidTagNormalizedSubject";
                Tag[Tag["PidTagObjectType"] = 4094] = "PidTagObjectType";
                Tag[Tag["PidTagOfficeLocation"] = 14873] = "PidTagOfficeLocation";
                Tag[Tag["PidTagOfflineAddressBookContainerGuid"] = 26626] = "PidTagOfflineAddressBookContainerGuid";
                Tag[Tag["PidTagOfflineAddressBookDistinguishedName"] = 26628] = "PidTagOfflineAddressBookDistinguishedName";
                Tag[Tag["PidTagOfflineAddressBookMessageClass"] = 26627] = "PidTagOfflineAddressBookMessageClass";
                Tag[Tag["PidTagOfflineAddressBookName"] = 26624] = "PidTagOfflineAddressBookName";
                Tag[Tag["PidTagOfflineAddressBookSequence"] = 26625] = "PidTagOfflineAddressBookSequence";
                Tag[Tag["PidTagOfflineAddressBookTruncatedProperties"] = 26629] = "PidTagOfflineAddressBookTruncatedProperties";
                Tag[Tag["PidTagOrdinalMost"] = 14050] = "PidTagOrdinalMost";
                Tag[Tag["PidTagOrganizationalIdNumber"] = 14864] = "PidTagOrganizationalIdNumber";
                Tag[Tag["PidTagOriginalAuthorEntryId"] = 76] = "PidTagOriginalAuthorEntryId";
                Tag[Tag["PidTagOriginalAuthorName"] = 77] = "PidTagOriginalAuthorName";
                Tag[Tag["PidTagOriginalDeliveryTime"] = 85] = "PidTagOriginalDeliveryTime";
                Tag[Tag["PidTagOriginalDisplayBcc"] = 114] = "PidTagOriginalDisplayBcc";
                Tag[Tag["PidTagOriginalDisplayCc"] = 115] = "PidTagOriginalDisplayCc";
                Tag[Tag["PidTagOriginalDisplayTo"] = 116] = "PidTagOriginalDisplayTo";
                Tag[Tag["PidTagOriginalEntryId"] = 14866] = "PidTagOriginalEntryId";
                Tag[Tag["PidTagOriginalMessageClass"] = 75] = "PidTagOriginalMessageClass";
                Tag[Tag["PidTagOriginalMessageId"] = 4166] = "PidTagOriginalMessageId";
                Tag[Tag["PidTagOriginalSenderAddressType"] = 102] = "PidTagOriginalSenderAddressType";
                Tag[Tag["PidTagOriginalSenderEmailAddress"] = 103] = "PidTagOriginalSenderEmailAddress";
                Tag[Tag["PidTagOriginalSenderEntryId"] = 91] = "PidTagOriginalSenderEntryId";
                Tag[Tag["PidTagOriginalSenderName"] = 90] = "PidTagOriginalSenderName";
                Tag[Tag["PidTagOriginalSenderSearchKey"] = 92] = "PidTagOriginalSenderSearchKey";
                Tag[Tag["PidTagOriginalSensitivity"] = 46] = "PidTagOriginalSensitivity";
                Tag[Tag["PidTagOriginalSentRepresentingAddressType"] = 104] = "PidTagOriginalSentRepresentingAddressType";
                Tag[Tag["PidTagOriginalSentRepresentingEmailAddress"] = 105] = "PidTagOriginalSentRepresentingEmailAddress";
                Tag[Tag["PidTagOriginalSentRepresentingEntryId"] = 94] = "PidTagOriginalSentRepresentingEntryId";
                Tag[Tag["PidTagOriginalSentRepresentingName"] = 93] = "PidTagOriginalSentRepresentingName";
                Tag[Tag["PidTagOriginalSentRepresentingSearchKey"] = 95] = "PidTagOriginalSentRepresentingSearchKey";
                Tag[Tag["PidTagOriginalSubject"] = 73] = "PidTagOriginalSubject";
                Tag[Tag["PidTagOriginalSubmitTime"] = 78] = "PidTagOriginalSubmitTime";
                Tag[Tag["PidTagOriginatorDeliveryReportRequested"] = 35] = "PidTagOriginatorDeliveryReportRequested";
                Tag[Tag["PidTagOriginatorNonDeliveryReportRequested"] = 3080] = "PidTagOriginatorNonDeliveryReportRequested";
                Tag[Tag["PidTagOscSyncEnabled"] = 31780] = "PidTagOscSyncEnabled";
                Tag[Tag["PidTagOtherAddressCity"] = 14943] = "PidTagOtherAddressCity";
                Tag[Tag["PidTagOtherAddressCountry"] = 14944] = "PidTagOtherAddressCountry";
                Tag[Tag["PidTagOtherAddressPostOfficeBox"] = 14948] = "PidTagOtherAddressPostOfficeBox";
                Tag[Tag["PidTagOtherAddressPostalCode"] = 14945] = "PidTagOtherAddressPostalCode";
                Tag[Tag["PidTagOtherAddressStateOrProvince"] = 14946] = "PidTagOtherAddressStateOrProvince";
                Tag[Tag["PidTagOtherAddressStreet"] = 14947] = "PidTagOtherAddressStreet";
                Tag[Tag["PidTagOtherTelephoneNumber"] = 14879] = "PidTagOtherTelephoneNumber";
                Tag[Tag["PidTagOutOfOfficeState"] = 26141] = "PidTagOutOfOfficeState";
                Tag[Tag["PidTagOwnerAppointmentId"] = 98] = "PidTagOwnerAppointmentId";
                Tag[Tag["PidTagPagerTelephoneNumber"] = 14881] = "PidTagPagerTelephoneNumber";
                Tag[Tag["PidTagParentEntryId"] = 3593] = "PidTagParentEntryId";
                Tag[Tag["PidTagParentFolderId"] = 26441] = "PidTagParentFolderId";
                Tag[Tag["PidTagParentKey"] = 37] = "PidTagParentKey";
                Tag[Tag["PidTagParentSourceKey"] = 26081] = "PidTagParentSourceKey";
                Tag[Tag["PidTagPersonalHomePage"] = 14928] = "PidTagPersonalHomePage";
                Tag[Tag["PidTagPolicyTag"] = 12313] = "PidTagPolicyTag";
                Tag[Tag["PidTagPostOfficeBox"] = 14891] = "PidTagPostOfficeBox";
                Tag[Tag["PidTagPostalAddress"] = 14869] = "PidTagPostalAddress";
                Tag[Tag["PidTagPostalCode"] = 14890] = "PidTagPostalCode";
                Tag[Tag["PidTagPredecessorChangeList"] = 26083] = "PidTagPredecessorChangeList";
                Tag[Tag["PidTagPrimaryFaxNumber"] = 14883] = "PidTagPrimaryFaxNumber";
                Tag[Tag["PidTagPrimarySendAccount"] = 3624] = "PidTagPrimarySendAccount";
                Tag[Tag["PidTagPrimaryTelephoneNumber"] = 14874] = "PidTagPrimaryTelephoneNumber";
                Tag[Tag["PidTagPriority"] = 38] = "PidTagPriority";
                Tag[Tag["PidTagProcessed"] = 32001] = "PidTagProcessed";
                Tag[Tag["PidTagProfession"] = 14918] = "PidTagProfession";
                Tag[Tag["PidTagProhibitReceiveQuota"] = 26218] = "PidTagProhibitReceiveQuota";
                Tag[Tag["PidTagProhibitSendQuota"] = 26222] = "PidTagProhibitSendQuota";
                Tag[Tag["PidTagPurportedSenderDomain"] = 16515] = "PidTagPurportedSenderDomain";
                Tag[Tag["PidTagRadioTelephoneNumber"] = 14877] = "PidTagRadioTelephoneNumber";
                Tag[Tag["PidTagRead"] = 3689] = "PidTagRead";
                Tag[Tag["PidTagReadReceiptAddressType"] = 16425] = "PidTagReadReceiptAddressType";
                Tag[Tag["PidTagReadReceiptEmailAddress"] = 16426] = "PidTagReadReceiptEmailAddress";
                Tag[Tag["PidTagReadReceiptEntryId"] = 70] = "PidTagReadReceiptEntryId";
                Tag[Tag["PidTagReadReceiptName"] = 16427] = "PidTagReadReceiptName";
                Tag[Tag["PidTagReadReceiptRequested"] = 41] = "PidTagReadReceiptRequested";
                Tag[Tag["PidTagReadReceiptSearchKey"] = 83] = "PidTagReadReceiptSearchKey";
                Tag[Tag["PidTagReadReceiptSmtpAddress"] = 23813] = "PidTagReadReceiptSmtpAddress";
                Tag[Tag["PidTagReceiptTime"] = 42] = "PidTagReceiptTime";
                Tag[Tag["PidTagReceivedByAddressType"] = 117] = "PidTagReceivedByAddressType";
                Tag[Tag["PidTagReceivedByEmailAddress"] = 118] = "PidTagReceivedByEmailAddress";
                Tag[Tag["PidTagReceivedByEntryId"] = 63] = "PidTagReceivedByEntryId";
                Tag[Tag["PidTagReceivedByName"] = 64] = "PidTagReceivedByName";
                Tag[Tag["PidTagReceivedBySearchKey"] = 81] = "PidTagReceivedBySearchKey";
                Tag[Tag["PidTagReceivedBySmtpAddress"] = 23815] = "PidTagReceivedBySmtpAddress";
                Tag[Tag["PidTagReceivedRepresentingAddressType"] = 119] = "PidTagReceivedRepresentingAddressType";
                Tag[Tag["PidTagReceivedRepresentingEmailAddress"] = 120] = "PidTagReceivedRepresentingEmailAddress";
                Tag[Tag["PidTagReceivedRepresentingEntryId"] = 67] = "PidTagReceivedRepresentingEntryId";
                Tag[Tag["PidTagReceivedRepresentingName"] = 68] = "PidTagReceivedRepresentingName";
                Tag[Tag["PidTagReceivedRepresentingSearchKey"] = 82] = "PidTagReceivedRepresentingSearchKey";
                Tag[Tag["PidTagReceivedRepresentingSmtpAddress"] = 23816] = "PidTagReceivedRepresentingSmtpAddress";
                Tag[Tag["PidTagRecipientDisplayName"] = 24566] = "PidTagRecipientDisplayName";
                Tag[Tag["PidTagRecipientEntryId"] = 24567] = "PidTagRecipientEntryId";
                Tag[Tag["PidTagRecipientFlags"] = 24573] = "PidTagRecipientFlags";
                Tag[Tag["PidTagRecipientOrder"] = 24543] = "PidTagRecipientOrder";
                Tag[Tag["PidTagRecipientProposed"] = 24545] = "PidTagRecipientProposed";
                Tag[Tag["PidTagRecipientProposedEndTime"] = 24548] = "PidTagRecipientProposedEndTime";
                Tag[Tag["PidTagRecipientProposedStartTime"] = 24547] = "PidTagRecipientProposedStartTime";
                Tag[Tag["PidTagRecipientReassignmentProhibited"] = 43] = "PidTagRecipientReassignmentProhibited";
                Tag[Tag["PidTagRecipientTrackStatus"] = 24575] = "PidTagRecipientTrackStatus";
                Tag[Tag["PidTagRecipientTrackStatusTime"] = 24571] = "PidTagRecipientTrackStatusTime";
                Tag[Tag["PidTagRecipientType"] = 3093] = "PidTagRecipientType";
                Tag[Tag["PidTagRecordKey"] = 4089] = "PidTagRecordKey";
                Tag[Tag["PidTagReferredByName"] = 14919] = "PidTagReferredByName";
                Tag[Tag["PidTagRemindersOnlineEntryId"] = 14037] = "PidTagRemindersOnlineEntryId";
                Tag[Tag["PidTagRemoteMessageTransferAgent"] = 3105] = "PidTagRemoteMessageTransferAgent";
                Tag[Tag["PidTagRenderingPosition"] = 14091] = "PidTagRenderingPosition";
                Tag[Tag["PidTagReplyRecipientEntries"] = 79] = "PidTagReplyRecipientEntries";
                Tag[Tag["PidTagReplyRecipientNames"] = 80] = "PidTagReplyRecipientNames";
                Tag[Tag["PidTagReplyRequested"] = 3095] = "PidTagReplyRequested";
                Tag[Tag["PidTagReplyTemplateId"] = 26050] = "PidTagReplyTemplateId";
                Tag[Tag["PidTagReplyTime"] = 48] = "PidTagReplyTime";
                Tag[Tag["PidTagReportDispositionMode"] = 129] = "PidTagReportDispositionMode";
                Tag[Tag["PidTagReportDisposition"] = 128] = "PidTagReportDisposition";
                Tag[Tag["PidTagReportEntryId"] = 69] = "PidTagReportEntryId";
                Tag[Tag["PidTagReportName"] = 58] = "PidTagReportName";
                Tag[Tag["PidTagReportSearchKey"] = 84] = "PidTagReportSearchKey";
                Tag[Tag["PidTagReportTag"] = 49] = "PidTagReportTag";
                Tag[Tag["PidTagReportText"] = 4097] = "PidTagReportText";
                Tag[Tag["PidTagReportTime"] = 50] = "PidTagReportTime";
                Tag[Tag["PidTagReportingMessageTransferAgent"] = 26656] = "PidTagReportingMessageTransferAgent";
                Tag[Tag["PidTagResolveMethod"] = 16359] = "PidTagResolveMethod";
                Tag[Tag["PidTagResponseRequested"] = 99] = "PidTagResponseRequested";
                Tag[Tag["PidTagResponsibility"] = 3599] = "PidTagResponsibility";
                Tag[Tag["PidTagRetentionDate"] = 12316] = "PidTagRetentionDate";
                Tag[Tag["PidTagRetentionFlags"] = 12317] = "PidTagRetentionFlags";
                Tag[Tag["PidTagRetentionPeriod"] = 12314] = "PidTagRetentionPeriod";
                Tag[Tag["PidTagRights"] = 26169] = "PidTagRights";
                Tag[Tag["PidTagRoamingDatatypes"] = 31750] = "PidTagRoamingDatatypes";
                Tag[Tag["PidTagRoamingDictionary"] = 31751] = "PidTagRoamingDictionary";
                Tag[Tag["PidTagRoamingXmlStream"] = 31752] = "PidTagRoamingXmlStream";
                Tag[Tag["PidTagRowType"] = 4085] = "PidTagRowType";
                Tag[Tag["PidTagRowid"] = 12288] = "PidTagRowid";
                Tag[Tag["PidTagRtfCompressed"] = 4105] = "PidTagRtfCompressed";
                Tag[Tag["PidTagRtfInSync"] = 3615] = "PidTagRtfInSync";
                Tag[Tag["PidTagRuleActionNumber"] = 26192] = "PidTagRuleActionNumber";
                Tag[Tag["PidTagRuleActionType"] = 26185] = "PidTagRuleActionType";
                Tag[Tag["PidTagRuleActions"] = 26240] = "PidTagRuleActions";
                Tag[Tag["PidTagRuleCondition"] = 26233] = "PidTagRuleCondition";
                Tag[Tag["PidTagRuleError"] = 26184] = "PidTagRuleError";
                Tag[Tag["PidTagRuleFolderEntryId"] = 26193] = "PidTagRuleFolderEntryId";
                Tag[Tag["PidTagRuleId"] = 26228] = "PidTagRuleId";
                Tag[Tag["PidTagRuleIds"] = 26229] = "PidTagRuleIds";
                Tag[Tag["PidTagRuleLevel"] = 26243] = "PidTagRuleLevel";
                Tag[Tag["PidTagRuleMessageLevel"] = 26093] = "PidTagRuleMessageLevel";
                Tag[Tag["PidTagRuleMessageName"] = 26092] = "PidTagRuleMessageName";
                Tag[Tag["PidTagRuleMessageProviderData"] = 26094] = "PidTagRuleMessageProviderData";
                Tag[Tag["PidTagRuleMessageProvider"] = 26091] = "PidTagRuleMessageProvider";
                Tag[Tag["PidTagRuleMessageSequence"] = 26099] = "PidTagRuleMessageSequence";
                Tag[Tag["PidTagRuleMessageState"] = 26089] = "PidTagRuleMessageState";
                Tag[Tag["PidTagRuleMessageUserFlags"] = 26090] = "PidTagRuleMessageUserFlags";
                Tag[Tag["PidTagRuleName"] = 26242] = "PidTagRuleName";
                Tag[Tag["PidTagRuleProviderData"] = 26244] = "PidTagRuleProviderData";
                Tag[Tag["PidTagRuleProvider"] = 26241] = "PidTagRuleProvider";
                Tag[Tag["PidTagRuleSequence"] = 26230] = "PidTagRuleSequence";
                Tag[Tag["PidTagRuleState"] = 26231] = "PidTagRuleState";
                Tag[Tag["PidTagRuleUserFlags"] = 26232] = "PidTagRuleUserFlags";
                Tag[Tag["PidTagRwRulesStream"] = 26626] = "PidTagRwRulesStream";
                Tag[Tag["PidTagScheduleInfoAppointmentTombstone"] = 26730] = "PidTagScheduleInfoAppointmentTombstone";
                Tag[Tag["PidTagScheduleInfoAutoAcceptAppointments"] = 26733] = "PidTagScheduleInfoAutoAcceptAppointments";
                Tag[Tag["PidTagScheduleInfoDelegateEntryIds"] = 26693] = "PidTagScheduleInfoDelegateEntryIds";
                Tag[Tag["PidTagScheduleInfoDelegateNames"] = 26692] = "PidTagScheduleInfoDelegateNames";
                Tag[Tag["PidTagScheduleInfoDelegatorWantsCopy"] = 26690] = "PidTagScheduleInfoDelegatorWantsCopy";
                Tag[Tag["PidTagScheduleInfoDelegatorWantsInfo"] = 26699] = "PidTagScheduleInfoDelegatorWantsInfo";
                Tag[Tag["PidTagScheduleInfoDisallowOverlappingAppts"] = 26735] = "PidTagScheduleInfoDisallowOverlappingAppts";
                Tag[Tag["PidTagScheduleInfoDisallowRecurringAppts"] = 26734] = "PidTagScheduleInfoDisallowRecurringAppts";
                Tag[Tag["PidTagScheduleInfoDontMailDelegates"] = 26691] = "PidTagScheduleInfoDontMailDelegates";
                Tag[Tag["PidTagScheduleInfoFreeBusy"] = 26732] = "PidTagScheduleInfoFreeBusy";
                Tag[Tag["PidTagScheduleInfoFreeBusyAway"] = 26710] = "PidTagScheduleInfoFreeBusyAway";
                Tag[Tag["PidTagScheduleInfoFreeBusyBusy"] = 26708] = "PidTagScheduleInfoFreeBusyBusy";
                Tag[Tag["PidTagScheduleInfoFreeBusyMerged"] = 26704] = "PidTagScheduleInfoFreeBusyMerged";
                Tag[Tag["PidTagScheduleInfoFreeBusyTentative"] = 26706] = "PidTagScheduleInfoFreeBusyTentative";
                Tag[Tag["PidTagScheduleInfoMonthsAway"] = 26709] = "PidTagScheduleInfoMonthsAway";
                Tag[Tag["PidTagScheduleInfoMonthsBusy"] = 26707] = "PidTagScheduleInfoMonthsBusy";
                Tag[Tag["PidTagScheduleInfoMonthsMerged"] = 26703] = "PidTagScheduleInfoMonthsMerged";
                Tag[Tag["PidTagScheduleInfoMonthsTentative"] = 26705] = "PidTagScheduleInfoMonthsTentative";
                Tag[Tag["PidTagScheduleInfoResourceType"] = 26689] = "PidTagScheduleInfoResourceType";
                Tag[Tag["PidTagSchedulePlusFreeBusyEntryId"] = 26146] = "PidTagSchedulePlusFreeBusyEntryId";
                Tag[Tag["PidTagScriptData"] = 4] = "PidTagScriptData";
                Tag[Tag["PidTagSearchFolderDefinition"] = 26693] = "PidTagSearchFolderDefinition";
                Tag[Tag["PidTagSearchFolderExpiration"] = 26682] = "PidTagSearchFolderExpiration";
                Tag[Tag["PidTagSearchFolderId"] = 26690] = "PidTagSearchFolderId";
                Tag[Tag["PidTagSearchFolderLastUsed"] = 26676] = "PidTagSearchFolderLastUsed";
                Tag[Tag["PidTagSearchFolderRecreateInfo"] = 26692] = "PidTagSearchFolderRecreateInfo";
                Tag[Tag["PidTagSearchFolderStorageType"] = 26694] = "PidTagSearchFolderStorageType";
                Tag[Tag["PidTagSearchKey"] = 12299] = "PidTagSearchKey";
                Tag[Tag["PidTagSecurityDescriptorAsXml"] = 3690] = "PidTagSecurityDescriptorAsXml";
                Tag[Tag["PidTagSelectable"] = 13833] = "PidTagSelectable";
                Tag[Tag["PidTagSendInternetEncoding"] = 14961] = "PidTagSendInternetEncoding";
                Tag[Tag["PidTagSendRichInfo"] = 14912] = "PidTagSendRichInfo";
                Tag[Tag["PidTagSenderAddressType"] = 3102] = "PidTagSenderAddressType";
                Tag[Tag["PidTagSenderEmailAddress"] = 3103] = "PidTagSenderEmailAddress";
                Tag[Tag["PidTagSenderEntryId"] = 3097] = "PidTagSenderEntryId";
                Tag[Tag["PidTagSenderIdStatus"] = 16505] = "PidTagSenderIdStatus";
                Tag[Tag["PidTagSenderName"] = 3098] = "PidTagSenderName";
                Tag[Tag["PidTagSenderSearchKey"] = 3101] = "PidTagSenderSearchKey";
                Tag[Tag["PidTagSenderSmtpAddress"] = 23809] = "PidTagSenderSmtpAddress";
                Tag[Tag["PidTagSenderTelephoneNumber"] = 26626] = "PidTagSenderTelephoneNumber";
                Tag[Tag["PidTagSensitivity"] = 54] = "PidTagSensitivity";
                Tag[Tag["PidTagSentMailSvrEID"] = 26432] = "PidTagSentMailSvrEID";
                Tag[Tag["PidTagSentRepresentingAddressType"] = 100] = "PidTagSentRepresentingAddressType";
                Tag[Tag["PidTagSentRepresentingEmailAddress"] = 101] = "PidTagSentRepresentingEmailAddress";
                Tag[Tag["PidTagSentRepresentingEntryId"] = 65] = "PidTagSentRepresentingEntryId";
                Tag[Tag["PidTagSentRepresentingFlags"] = 16410] = "PidTagSentRepresentingFlags";
                Tag[Tag["PidTagSentRepresentingName"] = 66] = "PidTagSentRepresentingName";
                Tag[Tag["PidTagSentRepresentingSearchKey"] = 59] = "PidTagSentRepresentingSearchKey";
                Tag[Tag["PidTagSentRepresentingSmtpAddress"] = 23810] = "PidTagSentRepresentingSmtpAddress";
                Tag[Tag["PidTagSmtpAddress"] = 14846] = "PidTagSmtpAddress";
                Tag[Tag["PidTagSortLocaleId"] = 26373] = "PidTagSortLocaleId";
                Tag[Tag["PidTagSourceKey"] = 26080] = "PidTagSourceKey";
                Tag[Tag["PidTagSpokenName"] = 36034] = "PidTagSpokenName";
                Tag[Tag["PidTagSpouseName"] = 14920] = "PidTagSpouseName";
                Tag[Tag["PidTagStartDate"] = 96] = "PidTagStartDate";
                Tag[Tag["PidTagStartDateEtc"] = 12315] = "PidTagStartDateEtc";
                Tag[Tag["PidTagStateOrProvince"] = 14888] = "PidTagStateOrProvince";
                Tag[Tag["PidTagStoreEntryId"] = 4091] = "PidTagStoreEntryId";
                Tag[Tag["PidTagStoreState"] = 13326] = "PidTagStoreState";
                Tag[Tag["PidTagStoreSupportMask"] = 13325] = "PidTagStoreSupportMask";
                Tag[Tag["PidTagStreetAddress"] = 14889] = "PidTagStreetAddress";
                Tag[Tag["PidTagSubfolders"] = 13834] = "PidTagSubfolders";
                Tag[Tag["PidTagSubjectPrefix"] = 61] = "PidTagSubjectPrefix";
                Tag[Tag["PidTagSubject"] = 55] = "PidTagSubject";
                Tag[Tag["PidTagSupplementaryInfo"] = 3099] = "PidTagSupplementaryInfo";
                Tag[Tag["PidTagSurname"] = 14865] = "PidTagSurname";
                Tag[Tag["PidTagSwappedToDoData"] = 3629] = "PidTagSwappedToDoData";
                Tag[Tag["PidTagSwappedToDoStore"] = 3628] = "PidTagSwappedToDoStore";
                Tag[Tag["PidTagTargetEntryId"] = 12304] = "PidTagTargetEntryId";
                Tag[Tag["PidTagTelecommunicationsDeviceForDeafTelephoneNumber"] = 14923] = "PidTagTelecommunicationsDeviceForDeafTelephoneNumber";
                Tag[Tag["PidTagTelexNumber"] = 14892] = "PidTagTelexNumber";
                Tag[Tag["PidTagTemplateData"] = 1] = "PidTagTemplateData";
                Tag[Tag["PidTagTemplateid"] = 14594] = "PidTagTemplateid";
                Tag[Tag["PidTagTextAttachmentCharset"] = 14107] = "PidTagTextAttachmentCharset";
                Tag[Tag["PidTagThumbnailPhoto"] = 35998] = "PidTagThumbnailPhoto";
                Tag[Tag["PidTagTitle"] = 14871] = "PidTagTitle";
                Tag[Tag["PidTagTnefCorrelationKey"] = 127] = "PidTagTnefCorrelationKey";
                Tag[Tag["PidTagToDoItemFlags"] = 3627] = "PidTagToDoItemFlags";
                Tag[Tag["PidTagTransmittableDisplayName"] = 14880] = "PidTagTransmittableDisplayName";
                Tag[Tag["PidTagTransportMessageHeaders"] = 125] = "PidTagTransportMessageHeaders";
                Tag[Tag["PidTagTrustSender"] = 3705] = "PidTagTrustSender";
                Tag[Tag["PidTagUserCertificate"] = 14882] = "PidTagUserCertificate";
                Tag[Tag["PidTagUserEntryId"] = 26137] = "PidTagUserEntryId";
                Tag[Tag["PidTagUserX509Certificate"] = 14960] = "PidTagUserX509Certificate";
                Tag[Tag["PidTagViewDescriptorBinary"] = 28673] = "PidTagViewDescriptorBinary";
                Tag[Tag["PidTagViewDescriptorName"] = 28678] = "PidTagViewDescriptorName";
                Tag[Tag["PidTagViewDescriptorStrings"] = 28674] = "PidTagViewDescriptorStrings";
                Tag[Tag["PidTagViewDescriptorVersion"] = 28679] = "PidTagViewDescriptorVersion";
                Tag[Tag["PidTagVoiceMessageAttachmentOrder"] = 26629] = "PidTagVoiceMessageAttachmentOrder";
                Tag[Tag["PidTagVoiceMessageSenderName"] = 26627] = "PidTagVoiceMessageSenderName";
                Tag[Tag["PidTagWeddingAnniversary"] = 14913] = "PidTagWeddingAnniversary";
                Tag[Tag["PidTagWlinkAddressBookEID"] = 26708] = "PidTagWlinkAddressBookEID";
                Tag[Tag["PidTagWlinkAddressBookStoreEID"] = 26769] = "PidTagWlinkAddressBookStoreEID";
                Tag[Tag["PidTagWlinkCalendarColor"] = 26707] = "PidTagWlinkCalendarColor";
                Tag[Tag["PidTagWlinkClientID"] = 26768] = "PidTagWlinkClientID";
                Tag[Tag["PidTagWlinkEntryId"] = 26700] = "PidTagWlinkEntryId";
                Tag[Tag["PidTagWlinkFlags"] = 26698] = "PidTagWlinkFlags";
                Tag[Tag["PidTagWlinkFolderType"] = 26703] = "PidTagWlinkFolderType";
                Tag[Tag["PidTagWlinkGroupClsid"] = 26704] = "PidTagWlinkGroupClsid";
                Tag[Tag["PidTagWlinkGroupHeaderID"] = 26690] = "PidTagWlinkGroupHeaderID";
                Tag[Tag["PidTagWlinkGroupName"] = 26705] = "PidTagWlinkGroupName";
                Tag[Tag["PidTagWlinkOrdinal"] = 26699] = "PidTagWlinkOrdinal";
                Tag[Tag["PidTagWlinkROGroupType"] = 26770] = "PidTagWlinkROGroupType";
                Tag[Tag["PidTagWlinkRecordKey"] = 26701] = "PidTagWlinkRecordKey";
                Tag[Tag["PidTagWlinkSection"] = 26706] = "PidTagWlinkSection";
                Tag[Tag["PidTagWlinkStoreEntryId"] = 26702] = "PidTagWlinkStoreEntryId";
                Tag[Tag["PidTagWlinkType"] = 26697] = "PidTagWlinkType";
                Tag[Tag["PidTagAssociatedContentCount"] = 13847] = "PidTagAssociatedContentCount";
                Tag[Tag["PidTagFolderChildCount"] = 26168] = "PidTagFolderChildCount";
                Tag[Tag["PidTagIpmPublicFoldersEntryId"] = 26161] = "PidTagIpmPublicFoldersEntryId";
                Tag[Tag["PidTagConversationKey"] = 11] = "PidTagConversationKey";
                Tag[Tag["PidTagContactEmailAddresses"] = 14934] = "PidTagContactEmailAddresses";
                Tag[Tag["PidTagGenerateExchangeViews"] = 14057] = "PidTagGenerateExchangeViews";
                Tag[Tag["PidTagLatestDeliveryTime"] = 25] = "PidTagLatestDeliveryTime";
                Tag[Tag["PidTagMailPermission"] = 14862] = "PidTagMailPermission";
                Tag[Tag["PidTagFolderFlags"] = 26280] = "PidTagFolderFlags";
                Tag[Tag["PidTagHierRev"] = 16514] = "PidTagHierRev";
            })(Tag = Property.Tag || (Property.Tag = {}));
        })(Property = MSG.Property || (MSG.Property = {}));
    })(MSG = MailReader.MSG || (MailReader.MSG = {}));
})(MailReader || (MailReader = {}));
//# sourceMappingURL=Property.js.map